[package]
name = "dnd_cli"
version = "0.1.0"
authors = ["jgf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
mockall = "0.9.0"